class LoginError(Exception):
    """Error thrown when logging in fails"""
